### PR TITLE
(feature) Add onConfigure callback

### PR DESCRIPTION
**Pull request by mqus**
Enables a workaround for #534 

I'm not sure how to ~~test~~ write tests for this and would appreciate some Guidance :)

### CODE REVIEW

**Comment by cassioseffrin** [comment]
@mqus Thanks for your efforts on this, this feature will be very useful for migrations!
When this commit is ready for production I will be the first to test it!

**Review by cassioseffrin — COMMENTED** [review]
I cannot see anything wrong, therefore I think it could be approved. 

I cannot figure out how to cover this change with a test.

**Review by dkaera — APPROVED** [review]

**Review by vitusortner — APPROVED** [review]
Thanks!

**Comment by cassioseffrin** [comment]
@vitusortner what do you think about having a branch with this feature in old floor 0.19.1 to be compatible with flutter 1x?

I have done it, if you agree with that I can make a PR. I think there are other devs with the same needs. Once flutter 2 (null safety) comes with a lot of refactoring needs and there are many libs that haven't support it yet.

**Pull request merged**
