### PR TITLE
transient annotation is implemented

### PR DESCRIPTION
**Pull request by Ghomi-Dev**
transient annotation is implemented to support the transient fields in entities

these fields should not be persisted to data tables in project's database and they only serve the data integrity

### CODE REVIEW

**Comment by Ghomi-Dev** [comment]
Hi ,
I was in need for transient annotated field in my entity definition, I didn't find it so I implemented it in the library

please review and let me know if there is any refactor is needed

Regards

description:

transient annotation is implemented to support the transient fields in entities

these fields should not be persisted to data tables in project's database and they only serve the data integrity

@vitusortner

**Comment by vitusortner** [comment]
Hi @Ghomi-Dev and thanks for your contribution! I'll review it as soon as possible.

**Comment by Ghomi-Dev** [comment]
> 
> 
> Hi @Ghomi-Dev and thanks for your contribution! I'll review it as soon as possible.

Hi @vitusortner 
Thanks for your kind reply, I will look forward to any pro tips you can give me to refactor or make the  code better

**Comment by SeyedAbbasGhomi** [comment]
Hi @vitusortner
I appreciate it if you review my pull request

**Comment by vitusortner** [comment]
Closed by #248

**Comment by cassioseffrin** [comment]
@Ghomi-Dev do you know when this feature @transient will be release. Next version?

**Comment by mqus** [comment]
`@ignore` annotations are available since v0.11.0 and should perform the exact same function. 
https://github.com/vitusortner/floor#ignoring-fields
(IMHO, `@ignore` is a better name than `@transient`)

**Comment by cassioseffrin** [comment]
@mqus, I am a hibernate user, so I still confusing the annotations names. Thks @ignore will be very useful!

**Pull request closed without merging**
