### PR TITLE
Change delete and update to allow string primary keys

### PR DESCRIPTION
**Pull request by North101**
PR for #164

### CODE REVIEW

**Comment by noordawod** [comment]
This is a very good patch! Any plans to merge it @vitusortner?

**Comment by dkaera** [comment]
This fix allows supporting just String primary keys, but I found the new issue. Update and delete adapters doesn't work correctly with group keys. I'll create PR with a fix, which will support `dynamic` primary keys, both single and group.

**Comment by noordawod** [comment]
That would be awesome, @dkaera! Thanks.

**Comment by vitusortner** [comment]
A complete fix for the problem got introduced by #181

**Pull request closed without merging**
